version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    ports:
      - "8000:8000"

    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres:15.4
    container_name: "database"

    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  database: