version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "app_dev"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres:15.4
    container_name: "database_dev"

    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=debug

volumes:
  database: