version: '3.9'

services:
  app:
    container_name: "app"

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app

    command: sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    depends_on:
      - database
  database:
    image: postgres:15.4
    container_name: "database"

    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  database: