version: '3.9'

services:

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_data:/vol/web
    depends_on:
      - app

  app:
    build:
      context: .
    
    volumes:
      - static_data:/vol/web
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 8000
    
    depends_on:
      - database

  database:
    image: postgres:15.4
    container_name: "database"

    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  static_data:
  database: