name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Pull request on 'main'
    - name: Build and Run Production Containers
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      run: |
        docker-compose up -d --build

    # Push to 'dev'
    - name: Build and Run Development Containers
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      run: |
        docker-compose -f docker-compose.dev.yml up -d --build
