name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Run this if the event is a pull request on 'main'
    - name: Build and Run Production Containers
      if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

    # Run this if the event is a push to 'dev'
    - name: Build and Run Development Containers
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      run: |
        docker-compose up -d --build
