name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

env: # Adding the non-sensitive .env.dev values here
  POSTGRES_DB: database
  POSTGRES_USER: root
  POSTGRES_PASSWORD: debug
  DJANGO_SECRET_KEY: django-insecure-*5-o#x+753^jm&0w@25pjim9h_w%bi=-j3b6x@4moye215*r-+

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Pull request on 'main'
    - name: Build and Run Production Containers
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      run: |
        echo "${{ secrets.PROD_RSA_PRIVATE_KEY }}" | base64 -d > app/key
        echo "${{ secrets.PROD_RSA_PUBLIC_KEY }}" | base64 -d > app/key.pub
        chmod 600 app/key
        chmod 644 app/key.pub
        docker-compose -f docker-compose-deploy.yml up -d --build
      env: # Override environment variables with GitHub Secrets
        POSTGRES_DB: ${{ secrets.PROD_POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.PROD_POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.PROD_POSTGRES_PASSWORD }}
        DJANGO_SECRET_KEY: ${{ secrets.PROD_DJANGO_SECRET_KEY }}


    # Push to 'dev'
    - name: Build and Run Development Containers
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      run: docker-compose up -d --build
